### ISSUE TITLE
:enoent File not found error

### ISSUE THREAD

**Issue by VTOL-wins** [coletiv/puppeteer-pdf#4]
I have been attempting to use puppeteer-pdf and was running the test module and keep running into a :enoent error. Do you have any insight into this error and any potential solutions?

Follows is the response from running the test. 

test Generate PDF using HTML (PuppeteerPdfTest)
     test/puppeteer_pdf_test.exs:5
     ** (ErlangError) Erlang error: :enoent
     code: {:ok, _} = PuppeteerPdf.generate_with_html(html, pdf_path)
     stacktrace:
       (elixir) lib/system.ex:622: System.cmd("puppeteer-pdf", ["/var/folders/0r/nn0z91l95y9gfwx2n3gls_yh0000gp/T/briefly-1529/briefly-513815-131414-3.html", "--path", "pdf_test.pdf"], [])
       (puppeteer_pdf) lib/puppeteer_pdf.ex:54: PuppeteerPdf.generate/3
       test/puppeteer_pdf_test.exs:9: (test)

**Comment by speeddragon** [comment]
I will check this issue tomorrow.

**Comment by speeddragon** [comment]
Finally took some time to look into it. The issue is `puppeteer-pdf` binary isn't available to use in your system. You can install it by running `npm install -g puppeteer-pdf`, and/or check [this](https://docs.npmjs.com/getting-started/fixing-npm-permissions) if you having some trouble with permission.

I will update the README.md to reflect that.

**Comment by VTOL-wins** [comment]
Thanks, it took some work arounds but I now have my environment set up.
